language: ruby
os: linux
dist: xenial
cache: bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

jobs:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.2.gemfile

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo sed -i -e "s/^port =.*/port = $PGPORT/" /etc/postgresql/*/main/postgresql.conf
  - sudo /etc/init.d/postgresql restart
  - sleep 2
  - psql -c "CREATE DATABASE chronomodel;" -U postgres
  - psql -c "CREATE DATABASE chronomodel_railsapp;" -U postgres
  - gem install simplecov -v '0.17.1'

env:
  global:
    - CC_TEST_REPORTER_ID=dedfb7472ee410eec459bff3681d9a8fd8dd237e9bd7e8675a7c8eb7e253bba9
    - PGPORT=5433

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake TEST_CONFIG=./spec/config.travis.yml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
